### ISSUE TITLE
Problems with a Windows 10 SRUM Database

### ISSUE THREAD

**Issue by hudsonhawk242** [devgc/SrumMonkey#3]
I am sorry my english is not to good. i got srum monkey working on a windows 10 machine and i pulled out the srum-db from a windows 10 system and i ran into the following errors:

Converting Table MSysObjects as MSysObjects
Converting Table MSysObjectsShadow as MSysObjectsShadow
Converting Table MSysObjids as MSysObjids
Converting Table MSysLocales as MSysLocales
Converting Table SruDbIdMapTable as SruDbIdMapTable
Converting Table SruDbCheckpointTable as SruDbCheckpointTable
Converting Table {973F5D5C-1D90-4944-BE8E-24B94231A174} as NetworkUsageData
Converting Table {D10CA2FE-6FCF-4F6D-848E-B2E99266FA89} as ApplicationResourceUsageData
Converting Table {97C2CE28-A37B-4920-B1E9-8B76CD341EC5} as {97C2CE28-A37B-4920-B1E9-8B76CD341EC5}
Converting Table {FEE4E14F-02A9-4550-B5CE-5FA2DA202E37} as WindowsPushNotificationData
Converting Table {D10CA2FE-6FCF-4F6D-848E-B2E99266FA86} as EnergyUsageData
Converting Table {DD6636C4-8929-4683-974E-22C046A43763} as NetworkConnectivityData
Converting Table {FEE4E14F-02A9-4550-B5CE-5FA2DA202E37}LT as WindowsPushNotificationDataLT
Traceback (most recent call last):
File "C:\Users\Student\Desktop\SrumMonkey-master\SrumMonkey.py", line 931, in
Main()
File "C:\Users\Student\Desktop\SrumMonkey-master\SrumMonkey.py", line 130, in Main
rhandler.EnumerateRegistryValues()
File "C:\Users\Student\Desktop\SrumMonkey-master\SrumMonkey.py", line 381, in EnumerateRegistryValues
self.INTERFACE_COLUMN_LISTING
File "C:\Users\Student\Desktop\SrumMonkey-master\SrumMonkey.py", line 808, in CreateTableFromMapping
field_mapping[field]
KeyError: u'Has Connected'

The Testfiles were perfectly working on my machine.

I also setup SrumMonkey running on a ubuntu 16.04 system and ran into the same errors (same database).

**Comment by devgc** [comment]
Try now. I think maybe this [commit](https://github.com/devgc/SrumMonkey/commit/59fdbd5c6311fa3db1f7458749478f0cadce5c37) fixed it. Let me know if the issue is resolved.
